  AWSTemplateFormatVersion: "2010-09-09"
  Description: Setup DNS Zone in Route53
  Parameters:
    Domain: 
      Type: String
      Description: Enter a domain to use when creating the zone.
  Resources: 
    DNSZone: 
      Type: "AWS::Route53::HostedZone"
      Properties: 
        Name: 
          Ref: Domain
  Outputs:
    Domain:
      Description: The domain setup by this script
      Value: 
        Ref: Domain
    HostedZoneId:
      Description: The Route53 ZoneId for this domain
      Value: 
        Ref: ZoneID
    NameServers:
      Description: The nameservers for the primary zone
      Value: 
        !Join [ ',',  !GetAtt DNSZone.NameServers ]